<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
 <head>
  <meta charset=utf-8">
  <title>_News_</title>
  <link rel="stylesheet" href="allnews.css">
 </head>
 <body>

<form name="test" method="post">
  <p><b>Header News:</b><br>
   <input type="text" size="40">
  </p>

  <p><b>Text News</b><Br>
   <textarea name="comment" cols="40" rows="3"></textarea></p>
  <p><input type="submit" value="Add News"></p>
 </form>

 </body>
</html>
